### ISSUE TITLE
NE performance analysis

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1082]
I've trialled NE on my analyst's PC.

The NE redraw typically takes 2 seconds (10M resolution).   The redraw for me is about 0.2 seconds.

The analysts currently run Debrief & NE data from network shared folders, under 64bit Win7.  I'm running locally on Ubuntu.   There's a chance that this is the difference, but I'd expect Debrief/GeoTools to already have the data cached - so only the first access would be across the network.

Anyway - I'd be interested in any performance improvements you can identify.

**Comment by pecko** [comment]
I suppose that this is for me.

**Comment by IanMayo** [comment]
Yes.  But, I suggest you don't spend more than two hours on it.  Right now I think it's only worth looking for large/significant blockages.

**Comment by pecko** [comment]
OK. On first glance, geotools looks fine; no leaks, it works faster when zoom in ...

**Comment by pecko** [comment]
Geotools uses Java NIO to read shp files, that is, it relies on Java/OS buffering/caching. It works fine when using local file system, but it is slow via networking.
BTW caching of local file system can worse performance because we do double caching (OS cache and our cache)

RE network share, we can do the following:

- move NE data folder to local file system if it's possible
- try to optimize networking (very general stuff)
- use the latest Java/OS (it is usually better optimized)

I have added option to enable memory mapped shape file via preference (the commit: https://github.com/debrief/debrief/commit/937b905ab5421c9a5d3ade0968d597b2f0724f81)
Seems, settings this option to true will enhance performance via network share. It will not any effect (or even worse) performance on local file system. This preference is false by default. You can set it to true on Windows with network share and test.

Notice: The user should have write permission on NE data folder because geotools write some index files to this directory. I'm not sure what happens if more user accessing the same data folder, but I think that it also can be issue on Windows.

**Comment by IanMayo** [comment]
I tried the new setting on a user PC.  I *looked like* it ran faster, though not a lot.  I suggest we make the value **True** by default.

**Comment by pecko** [comment]
I have made the memory mapped preference **True** by default.

Notice: Best performance are when data folder is on local disk and memory mapped=false.

**Comment by IanMayo** [comment]
Ok, implemented.
