### ISSUE TITLE
Change New Plot Wizard to reflect Natural Earth

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1084]
Aah, I've just thought of one last NE change.

We have the New Plot Wizard.  It asks the user if they want to view a Coastline or ETOPO data.

NE replaces both of these.  So, could you update the wizard to reflect this?

Here's an image to include on the NE page:
![ne_gib3](https://cloud.githubusercontent.com/assets/1108513/5977579/1c509af6-a891-11e4-80dd-5e5c4a368416.png)

* Title: "Add Vectored background data"
* Subtitle: Use this page to add the Natural Earth dataset to your plot.  
* Also: Could we also find a way to add a link to: https://github.com/debrief/NaturalEarth
* Then just have the "Include" option.

**Comment by pecko** [comment]
The commit: 

Added:

- icon for the Debrief Plot menu (it was eclipse's sample.gif)
- new file name is now new_plot.dpf instead of new_plot.xml

If NE data folder isn't set the wizard will create the following link:

Natural Earth data folder isn't set. Debrief will use the default folder.
You can set a data folder by clicking **Window>Preferences>Maritime analysis>Natural Earth**

Clicking link will open the NE preferences page.
If the NE data folder isn't set, the message with dialog will not be shown.

> Also: Could we also find a way to add a link to: https://github.com/debrief/NaturalEarth

We probably can add it, but I'm not sure what exactly you want.

Screenshot: 
![plotwizard](https://cloud.githubusercontent.com/assets/534584/5990443/ca79da4a-a9b1-11e4-96bf-8d49902a8165.png)

**Comment by IanMayo** [comment]
**RE: Natural Earth** could you include this, following the existing text:

Natural Earth data trimmed to suit Debrief's Mercator projection is available online from here:  https://github.com/debrief/NaturalEarth

**Comment by IanMayo** [comment]
We should also include that phrase in the Natural Earth preferences page.

**Comment by pecko** [comment]
Added link with https://github.com/pecko/debrief/commit/cb822f1400c6a2654cf8b857be08ac015cb4a56f

The link will be open in the default external browser.

**Comment by IanMayo** [comment]
Great solution, thanks.
