### ISSUE TITLE
Register TXT files with plot editor

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1122]
I'm most of the way through my AIS file importer.     I'm working in the branch titled: ````1118_ais_text_files````

But, I have two problems:

1.  Assign icon, and register with Plot editor.
![ais_files](https://cloud.githubusercontent.com/assets/1108513/6619986/f20c3b60-c8c5-11e4-9143-c10f7216a071.png)

It's possible to drag AIS (txt) files into Debrief.  But, it's not possible to open them from the Navigator.  As you can see in the above image, they aren't registereed.

So, I'd like you to play with the debrief.core plugin.xml so that in the Navigator **.txt** files are shown with the same icon that we use for .csv files.  I'd also like you to register the AIS file format so that users can right-click on a .txt file in the Navigator and select **Debrief Plot Editor**.

2.  Verifying contents of AIS file when opened from navigator.  It's a pain that my users receive their AIS data with a txt  suffix.  But, they get lots and lots of them, so it isn't an option to rename them.

So, we need to support the txt suffix.  As a safer way of handling this, I've implemented a regexp checker in the importer  (BaseLoader) that reads the first line and compares it with the regexp (if supplied) in the DebriefPlotLoader extension schema type.

The regexp checker receives the full path to the subject file when it's dragged in.  But, when I right-click on a .txt file, select *Other...* and select the Debrief plot editor, only the filename seems to get passed - not the rest of the path, so my file-reading regexp content matcher is failing.

Could you investigate how to get the whole path to the BaseLoader.canLoad() method?

**Comment by pecko** [comment]
I have added the https://github.com/pecko/debrief/commit/7839ba1e166365c34d580ab7f4b29c64a83f9fd2 commit to the 1118_ais_text_files branch. The commit adds the following features:

- get the whole path to the BaseLoader.canLoad() method
- describe the org.mwc.debrief.contenttype.AISTrackFile content type in more details, so we get Debrief Plot icon (and editor) in navigator. See AISContentDescriber.java
Currently, the file is recognized as AIS file if it contains "!AIVDM" string. I avoid using regular expression because it can affect performance (content describer is called often, but regexp is slow operation). Of course, we can change it.

**Comment by IanMayo** [comment]
So, I should now remove the "regexp" support since its unnecessary, right?

**Comment by pecko** [comment]
Right, You should.
