### ISSUE TITLE
Investigate Auto-Save

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1155]
A user lost his network connection, and Debrief (which was running off a network share) crashed.

On-site IT staff looked in to Debrief prefs, and saw the "Auto save workspace" settings.  

Investigate if this would effectively give timed auto-saves.

Don't take this further than an investigation though - some users rely on plots not being saved.

**Comment by pecko** [comment]
I think that you saw E4 preference. It will not save editors. 
Eclipse team avoid editor saving because it causes incremental build. Since, Debrief doesn't build something it isn't issue in Debrief.
We could adapt the external plugin as https://github.com/mystilleef/eclipse4-smartsave or similar for plot's (editor) saving.

**Comment by IanMayo** [comment]
The user saw this preference, in 3.8.2:
![workspace_save_interval](https://cloud.githubusercontent.com/assets/1108513/6960495/de0b8bd8-d91a-11e4-9f02-899fafefd95e.png)

But, I don't know if its saving the open files, or the workspace layout/preferences.

**Comment by pecko** [comment]
It is certainly not saving the open files since such feature doesn't exist in Eclipse.
There is a property to save workspace settings (layout/preferences). 
There is also a preference for automatically saving open files before building. This preference requires that something initiate a build and will save files that are covered by build (in the same projects).

**Comment by IanMayo** [comment]
ok, let's not bother. Closing issue.
