### ISSUE TITLE
New Bearing Residuals plot items too small

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1233]
The SWT version of the Bearing Residuals plot uses smaller axis fonts and symbols.

Legacy version:
![residuals_java](https://cloud.githubusercontent.com/assets/1108513/7569040/19bf7eee-f7fe-11e4-94d7-d0d7d873b260.png)

SWT version:
![residuals_swt](https://cloud.githubusercontent.com/assets/1108513/7569028/0ea73e2a-f7fe-11e4-9b2c-8b44592f7bbc.png)

Actually, they aren't that much different.  It just looks like tidying of the time axis is needed.

**Comment by pecko** [comment]
I have tried and there isn't much difference on my machine:

Swt:

![image](https://cloud.githubusercontent.com/assets/534584/7600610/0491f488-f90d-11e4-992c-8167d955017a.png)


Swing:

![image](https://cloud.githubusercontent.com/assets/534584/7600632/486c05fe-f90d-11e4-8993-f7e01d3b82f7.png)

**Comment by pecko** [comment]
JFreeChart calculates a font in SWTUtils.toSwtFontData
(http://sourceforge.net/p/jfreechart/code/HEAD/tree/branches/jfreechart-1.0.x-branch/swt/org/jfree/experimental/swt/SWTUtils.java)
It uses fixed DPI value: 72. Because of that fonts can look differently on different DPI.
I suppose that you have better monitor.

I'm not sure what to do here. We can change it, but there are two issues:

- we should change jfreechart code (I think that it is similar to #1218)
- not sure what DPI value to select. Geotools (org.geotools.renderer.lite.RendererUtilities.getDpi) uses 90 (25.4 / 0.28;   // 90 = OGC standard), but I get bigger SWT fonts in this case.

I have created the issue1233 branch that includes jfreechart plugin with the swt part as source. You can experiment on your machine with changing SWTUtils.toSwtFontData

**Comment by IanMayo** [comment]
Have done some formatting of the graph. Things look ok now.
