### ISSUE TITLE
PDF Cheat Sheet not being built

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1239]
Our MVN build is meant to create a PDF version of the Debrief cheat sheets.

But, it's currently failing when run from the IDE or the command line.

I *think* it runs ok from Travis - since the PDF version tutorial is present in each release.

It's a really tricky area - but I'd appreciate you investigating the problem.

**Comment by pecko** [comment]
I can't reproduce the issue from command line. I suppose that you use different Maven, Java or both versions. Could you send output of the following command:

mvn -version

My output is:

Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /usr/local/apache-maven-3.2.3
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /usr/local/jdk1.7.0_71/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-52-generic", arch: "amd64", family: "

Re build in IDE, I don't try it, but it can be caused by the same reason, that is, incompatible Maven and/or Java.

**Comment by IanMayo** [comment]
Aah, yes - it must be machine specific.  I see the Travis build does run satisfactorily.

Here is my command line config:
````
ian@loftymay14:~$ mvn -version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-52-generic", arch: "amd64", family: "unix"

````

I've just been able to use the ```` sudo update-alternatives --config javac ```` command to switch back to Java 7.

Aah, then I needed to meddle with /etc/profile.d/jjdk.*

I then go this version info:
````
ian@loftymay14:~/git/debrief/org.mwc.debrief.help$ mvn -version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-53-generic", arch: "amd64", family: "unix"
````

I see my mvn is a different version to yours.  I also see that Travis is using version 3.2.5

Maybe I should investigate updating my maven.

**Comment by pecko** [comment]
You can try build with maven 3.0.5 and your jdk 7.
Anyway, I think that you have version incompatibility issue.

**Comment by IanMayo** [comment]
Resolved.  The DITA build for the cheat sheets can handle Java 7 or 8 and Maven 3.0.x or 3.2.x.  But, it needs Ant 1.9.4 rather than Ant 1.9.3

Will document this.
