### ISSUE TITLE
Build breaking

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1271]
@pecko - the master build is breaking every time:
https://travis-ci.org/debrief/debrief/builds/66542379

It's the master branch that is failing, not development branches.

I think it's failing as it builds the products at the very last step.  Maybe it's related to build size - maybe we're reaching the limit again.

**Comment by pecko** [comment]
I have restarted the build in order to check. There are very small difference between previous build (succeed). I think that we sometime face some time/process limit that depends on current travis load (not only on our build).
If I'm correct and this issue becomes intolerable, we will have to contact travis stuff for help (increasing some limits or similar).
If it size problem, then we will have to remove some unnecessary stuff.

**Comment by IanMayo** [comment]
Great advice, thanks.

**Comment by pecko** [comment]
It fails again. I have seen that, but it worked second time. Checking more ...

**Comment by pecko** [comment]
The PR https://github.com/debrief/debrief/pull/1270 succeed (the build https://travis-ci.org/debrief/debrief/builds/66557062). It is the same as current master, so, I still think that it's some temporary limit caused by current travis load. I will restart the build again, and, if it works, will contact travis stuff.

**Comment by pecko** [comment]
The following are travis build timeout: http://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts
These times depend on Travis hardware and current temporary load and ca be different for the same code.
However, we recently introduce o.m.d.editable.test that lasts 2+ minutes. It is not too much, but maybe make major difference. IMO, our build takes cca half hour on travis. Will check on my local machine too.

**Comment by pecko** [comment]
Fails again.

Will create fake PR that will skip the editable test.

**Comment by pecko** [comment]
It works without the editable test. Maybe temporary. Now, I have removed the media plugin (we don't use it).

**Comment by IanMayo** [comment]
Hm, isn't the editable test so slow because it runs as a RCP JUnit test?  Can't we run it as plain JUnit test?

**Comment by pecko** [comment]
Not sure, but it would be hard. We have to set environment so we can find all Editable classes in hierarchy, instantiate them and call tests on them.
In Eclipse, we already have the projects with classpath, JDT to find hierarchy ...
Anyway, it would take probably the same (or more time). The editable test isn't slow (2 minutes from total 15 minutes on my machine), but, seems, reaches limit.

**Comment by pecko** [comment]
IMO, there are some weird issue with travis because the your PR (the same as current master) built properly.

**Comment by IanMayo** [comment]
Ok, I'm happy to treat this issue as "Travis being screwy".

Shall I close it?

**Comment by pecko** [comment]
I will try something yet.

**Comment by pecko** [comment]
After that, we can close this issue, but I will follow Travis builds.

**Comment by pecko** [comment]
I have just chaged commit message and the build for this PR fails. So, it is definitely some travis issue. However, we are nearly to some travis limit and have to think about some solution. Maybe contact Travis team.

**Comment by pecko** [comment]
Now, the master build (https://travis-ci.org/debrief/debrief/builds/66560510) is fine (without the PR mentioned above).
We can close this issue for now.

**Comment by IanMayo** [comment]
Closing.
