### ISSUE TITLE
"Graphic is disposed" error with SATC

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1303]
@russcrowley - a technical author is running through SATC and is getting a "graphic is disposed" error:
https://www.copy.com/s/t%3A9dtgn8fABTdOS1l8%3Bp%3A%252FError%2520Outline-1.mp4

Here is a copy of his log [with some repeated "graphic is disposed" errors deleted]
http://pastebin.com/5FsuXrB2

From the video I can see he is using the **L2_Scenario.dpf" file.

I'm unable to reproduce the error, I may have to watch him produce it in a Skype call.  Or, it may have been fixed in a Debrief update.

**Comment by russcrowley** [comment]
Ian, I ran the scenario again this morning and the L2_Scenario.dpf file I have has data that was added since I first started exploring Debrief. As such, I couldn't replicate some of the steps the tutorial specified were needed. I subsequently re-ran the tutorial using the L2_Scenario_clean.dpf file you provided and there were no errors in the outline view, and the scenario played out as per the tutorial. I recorded a video showing the process and will post a link once the video has rendered, converted, and uploaded.

**Comment by russcrowley** [comment]
https://copy.com/SKPAEPzQCptIrYWf

**Comment by IanMayo** [comment]
@russcrowley - could you email me your L2_Scenario.dpf file?  I'll look inside to see if there's something inconsistent in it that we aren't recognising/managing.

**Comment by IanMayo** [comment]
Russ's scenario file is attached. I can't see any problems inside it. When I load it into Debrief I can't reproduce his problem.  

[L2_Scenario_Russ.dpf | uploaded via ZenHub](https://files.zenhub.io/55a37b9bcbe0401050bda5bb)

I suspect the problem may be associated with some sequence of closing and re-opening views, with Debrief not cleanly de-registering a listener.

But, we'll have to close the issue until we've got something reproducible.
