### ISSUE TITLE
Dropping cheat sheets

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1335]
We're dropping support for cheat sheets.  We'll keep the sources in the repo "just in case". 

We need the following steps to remove them:
* [ ] don't register them in the plugin
* [ ] Swap any reference from the welcome page to a link to one of the two PDF documents.

Anything else @pecko ?

**Comment by pecko** [comment]
You mean that we replace all tutorials links with one link to tutorial pdf? 

BTW I think that you mentioned all required steps.
If we keep source, we will be able to open cheat sheet with entering url manually.

**Comment by IanMayo** [comment]
There will be just two PDF tutorials: a "Debrief Tutorial" and "TMA skills with Debrief".  The links will just go to the PDFs that we put in the installation folder.

**Comment by pecko** [comment]
OK. Will add it today later.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1337

If you want to test links, you have to create distribution, because PDF files are created while building.

The following is tutorials page (maybe you want change something):

![image](https://cloud.githubusercontent.com/assets/534584/9529750/5a5f87e8-4cfc-11e5-83f0-1fd530262a0b.png)

**Comment by IanMayo** [comment]
looks great - will review tomorrow AM
