### ISSUE TITLE
DIS Preferences window

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1427]
For the future DIS support, we need a preferences window. 

See this mockup:
![DIS mockup](https://docs.google.com/drawings/image?id=sNn-TlZXNZotVIU_bptFqtw&rev=838&h=567&w=601&ac=1)

**Comment by pecko** [comment]
This issue seems as duplicate of #1428

**Comment by IanMayo** [comment]
No. One is the control view, and one is the preferences window.

**Comment by pecko** [comment]
OK. Will add both in the same plugin.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1436

Screenshot:

![dispreferences](https://cloud.githubusercontent.com/assets/534584/12374335/a228987e-bc98-11e5-9b15-9272f716b082.png)

@IanMayo 

Could you please review/apply the PR. I will need the plugin in order to add DIS view (probably tomorrow).

**Comment by pecko** [comment]
The plugin checks that executable exists as well as that IP and port are valid, but doesn't include some logic (discovering).

**Comment by IanMayo** [comment]
Fixed in #1436
