### ISSUE TITLE
Ian stuck with Eclipse Properties

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1430]
I'm pleased with the progress in my issue1417_limpet_arch branch, particularly when it comes to properties.

Once we have a datafile open (such as boat1.rep), we can click on Limpet/Limpet Action and create some data.

Debrief correctly shows the properties for these new Limpet items.

But, the properties aren't editable.  I know we're creating the correct type of property (TextPropertyDescriptor, not PropertyDescriptor).

@pecko  - would you mind tracking what is happening, to find out why the properties aren't editable?

Note: our new property editors are retrieved in EditableWrapper.getPropertyDescriptors

That seems to be working properly.

cheers,
Ian

**Comment by pecko** [comment]
@IanMayo 

I will start it asap. How it's urgent?

**Comment by IanMayo** [comment]
Hmm, I think my preferred order is this fix first, then the #1429, which will allow me to start DIS coding next week.

But, it's not urgent - it's just the first task.

**Comment by pecko** [comment]
OK. My plan is today later or (probably) tomorrow.

**Comment by IanMayo** [comment]
Ok. I've just pushed my 1417 branch, so you have all my updates.

There have been a few limpet commits, but not many.

**Comment by pecko** [comment]
Fine.

**Comment by IanMayo** [comment]
@pecko - thanks for the UI tasks.

I'd appreciate this one next, please - it's quite a pain.

**Comment by pecko** [comment]
@IanMayo You're welcome.

I will start it asap.

**Comment by pecko** [comment]
The issue happens because Debrief doesn't use standard Eclipse property descriptors than its EditorType.

The PR: https://github.com/debrief/debrief/pull/1442 (against issue1417_limpet_arch) branch solve issue so adds default properties in DebrieIProperty and implementing getInfo (returns EditorType) for ItemWrapper. We should implement getInfo for each class we want to have editing properties.

@IanMayo 

Could you please review? After that and fixing #1441 we should rebase the issue1417_limpet_arch (maybe merge). Rebasing will be harder if you add a lot code here.

**Comment by IanMayo** [comment]
Fixed.
