### ISSUE TITLE
Hide/disable search boxes from specific fields in NatTable viewer

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2042]
Hi there @fipro78,
we've got a minor outstanding UI issue.  For the two columns that don't have *checkbox* search fields, it's still possible for the user to put the cursor into that field.  But the user won't understand the **SELECT ALL** text it contains, or knows how to provide a query string.

So, is it possible to disable the search/filter box for these columns?

![image](https://cloud.githubusercontent.com/assets/1108513/21976564/617fa108-dbca-11e6-93ed-caebb5261ed8.png)

**Comment by fipro78** [comment]
Yes of course. I thought I did this already, but the always editable configuration of the filter row is set via FilterRowDataLayer.

Add the following to the `NarrativeViewerFilterRowConfiguration` to disable the editing in the filter row in general. The configuration to enable this only for the two combo boxes is already there.

`configRegistry.registerConfigAttribute(
		EditConfigAttributes.CELL_EDITABLE_RULE, 
		EditableRule.NEVER_EDITABLE,
		DisplayMode.NORMAL,
		GridRegion.FILTER_ROW);`

**Comment by fipro78** [comment]
BTW, in your screenshot I see that you enabled the combo box also for the _Entry_ column. Is this by intention or accidentally because you removed the _Date_ column from the initial example? I just ask because IMHO it doesn't make much sense to provide a combo box filter for the _Entry_ column as the entries should be different for every entry and therefore it also brings in a performance issue for collecting the possible values.

**Comment by IanMayo** [comment]
@fipro78 - aah, I've made the **NEVER_EDITABLE** fix, and was just wondering about that combo box.  I'll hunt down the line where it's configured.

**Comment by IanMayo** [comment]
Fixed in: https://github.com/theanuradha/debrief/pull/2
