### ISSUE TITLE
M7.2.2 Produce code to expose object models - Second Bucket of 8

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3424]
Call the constructor and write the wrappers
Write a unit test for each wrapper
30 mins per object- check no exceptions is thrown. Testing diff parameters
Add the line for code completion to the wrappers
Second bucket of 8 = 4 hours
Code Review 1 hour

**Comment by saulhidalgoaular** [comment]
* Chart:
 - createScale()
 - createGrid()
 - createCoastPainter()
 - createETOPOPainter()
 - loadCoastline()

* Core:
 - clear()

* Utils
 - getClipboard()
 - setClipboard()

**Comment by helenayele** [comment]
@saulhidalgoaular and @IanMayo  , the tested scripts and as well the issues faced while testing the above functionalities are found in this doc : https://docs.google.com/document/d/1nDHFUw4Pywll5dD3kMIjYaq9s9SngGNvamLK6DHcRBg/edit
And I can't find clear() method in Debrief modules, Is this intentional?
