### ISSUE TITLE
M1.6.2.0.3 Automate build of new Debrief-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3523]
The new Debrief-Lite builds and runs from Eclipse, but for our Continuous Integration (CI) we need it to run from the command line.

The CI runs via Maven, but building Debrief-Lite via Maven proved a challenge (because of the local dependencies, I believe).  So, we're going to build it in Ant, but trigger that Ant build from Maven.

**Comment by ayeshare** [comment]
There is still an issue pending on this. We could not have a single jar for debrief-lite, instead the build generates a zip that contains a runnable jar and all the referenced jars inside the lib folder.  
The one-jar task that was used earlier for debrief-legacy could not load the LocaleUtils in gt-swing-tools, because the class loader could not load the locale properties file.  Onejar being old and not having support, it could not be pursued.  Eclipse JDT provides a jar in jar class loader, which requires the eclipse environment to make a build and therefore this needs more investigation.
