### ISSUE TITLE
D-Lite View ribbon fixes

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3665]
* [ ] When D-Lite starts, no zoom mode is active.  We should start off in Zoom-In mode.
* [ ] The 3 mouse modes  (pan, zoom-in, zoom-out) are radio buttons. The UI should reflect this
* [ ] The mouse modes should be grouped in a tab called `Mouse mode`
* [ ] We can remove `Selector` and `Info` buttons
* [ ] We should rename `Reset` as `Fit to window` and use the relevant icon

We have an updated UI for this panel:
https://projects.invisionapp.com/share/M8PY9ZONZHC#/screens/342699158

**Note**: the UI includes separators.  I can't find separators in the Ribbon API.  _Maybe_ a plain Swing menu separator would work.  If the separator isn't visible, try this fix: https://stackoverflow.com/a/3197757/92441

**Comment by ayeshare** [comment]
For separators we can use ribbonBand.startGroup();

**Comment by IanMayo** [comment]
Hey @saulhidalgoaular  - @ayeshare has found out how to do separators. See above.

**Comment by saulhidalgoaular** [comment]
oh. Thanks. Yes, I am going to use them in the Time Controller Section.

**Comment by ayeshare** [comment]
Cant find a way to start map in zoomin mode.  Saw this method: mapPane.setState(JMApPane.ZoomIn), but it doesnt work on this version of jmappane.

**Comment by IanMayo** [comment]
@ayeshare - fixed it here: https://github.com/debrief/debrief/pull/3678

I just manually fired the "ZoomInAction" action.

**Comment by helenayele** [comment]
Tested the following functionality:

- When D-Lite starts in Zoom-In mode

- The 3 mouse modes (pan, zoom-in, zoom-out) are working as expected

- No Selector and Info buttons are shown in the debrief-lite

- Reset is renamed as Fit to window and with relevant icon

Some minor issues 

1. But @IanMayo "The mouse modes should be grouped in a tab called Mouse mode"  , I can only see that those 3 mouse modes are grouped as views , is this by design? 

1. I only can see one separator on those buttons ,is this by design? [![Image from Gyazo](https://i.gyazo.com/fdb6e905251dfa5e83d4a5b317783045.png)](https://gyazo.com/fdb6e905251dfa5e83d4a5b317783045)
2. It has some difference from the design doc here - 
 [![Image from Gyazo](https://i.gyazo.com/0e148930613102f12a5e96eefe45a89c.png)](https://gyazo.com/0e148930613102f12a5e96eefe45a89c)
