### ISSUE TITLE
D-Lite is slow while loading large files

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3821]
D-Lite  takes more than 1 minute and 10 second  to load narrative_large.rep  large files.
But Full debrief load this same file in a second.

And this degrades its value to our users.

**Comment by IanMayo** [comment]
This is important, but not urgent, since D-Lite users will initially work with low volume data.

My suspicion is that we're doing screen redraws after each line of narrative is read in.

If this is the case, I guess we should tell Layers to pause sending modification events, until the whole file is read in.

**Comment by helenayele** [comment]
Yes , I tried BULK_RED_TRACKS.rep which is  larger  in size (2.6 mb) than narrative_large.rep (682 KB) and D-Lite takes only 10 seconds to load this larger file. So your suspect the right thing I think.

**Comment by IanMayo** [comment]
Ok, the error isn't what I was expecting.

The error is because we generate a full Outline tree at the end of loading the files.  There are 200 tracks in this scenario, each has 100 positions.

We should modify `SwingLayerManager` behaviour so that we defer populating a node until we open it - like we do in SWT.

Here's an article that covers lazy population of a JTree:
https://stackoverflow.com/questions/6252462/jtree-lazy-load-expand

**Comment by ayeshare** [comment]
Is this still a problem?  I think it takes a little more time the first tim, it loads any file because of class loader loading.  Otherwise I dont see a problem now.

**Comment by helenayele** [comment]
It's speed is now highly improved and it took around 5-7 seconds to load narrative_large.rep file. And its speed to load large dpf files is also good. Hence closing..

**Comment by helenayele** [comment]
Now to load narrative_bulk.rep files, it takes 8 seconds and to load narrative_large.rep file it takes around 2 seconds. If we can improve the loading time, we can see it in separate bug #4202
