### ISSUE TITLE
ConcurrentModificationException while draging Time slider back and forth

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3848]
While playing in Snail mode, when I slide manually back and forth, I get ConcurrentModificationException. And it shows some extra lines on the map.
![image](https://user-images.githubusercontent.com/31482729/54417552-9027f800-4713-11e9-8e81-6d4c95ade5b4.png)
[Concurrent_Modification_Exception.txt](https://github.com/debrief/debrief/files/2970001/Concurrent_Modification_Exception.txt)

###Steps:
1. Load boat1.rep and boat2.rep files
2. In Time menu, change the mode to Snail, try to play
3. While playing move the time slider back and forth. Repeat sliding sometime, then you will see the exception logged and some lines on the map.

**Comment by IanMayo** [comment]
Yes, this is almost certainly a threading problem.

We're stepping through the list of items to plot, but the method get called again, from another thread, which tries to build up the list of items.

I'm not sure of the correct fix.  We could take a copy of the `_oldWatchables` hashmap at the start of `newTime()`, or we could try to use some locking mechanism.  But, I wouldn't want that to block the UI.

Or, we just disable the time slider when we're stepping forward.

**Comment by helenayele** [comment]
No more reproducible, hence closing..

**Comment by IanMayo** [comment]
Yes - this was fixed in early July. The issue was that a static WorldLocation variable was being used in toScreen() and toWorld() conversions.  Threading issues meant that one thread could be writing new values to the variable while another thread was still reading it.

The commit was here:
https://github.com/debrief/debrief/pull/4399/commits/6486588a76a144dee05477624987fda5cb8094c0
