### ISSUE TITLE
Sometimes the default selected time format doesn't match to the time displays

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3875]
This happens when we open dpf files saved with non-default time format.
[![Image from Gyazo](https://i.gyazo.com/bee2c8f4d157d29abbd00447df496460.png)](https://gyazo.com/bee2c8f4d157d29abbd00447df496460)

### Steps to reproduce:
1. Launch D-Lite
2. Open boat1.rep file
3. Open Time menu , change the time format to ddHHmm
4. Drag again boat2.dpf file , 
Note that boat2.dpf should have the default selected time format while saved.
5. Now see the time format selected and what is applied on the time displays.

**Comment by IanMayo** [comment]
Ok. The underlying issue here is that the time format is saved in the `.dpf` file.  It looks like we correctly process the date format, put it into the time manager, and update the time label.  

But, when we do that, we also have to refresh the contents of the date format drop-down, so it marks the correct menu item as selected.

**Comment by helenayele** [comment]
Re-opened since #3882#pullrequestreview-217182808 is still reproducible

**Comment by IanMayo** [comment]
Demoting, to next release.

**Comment by saulhidalgoaular** [comment]
Good morning @helenayele . I have pushed another branch. https://github.com/debrief/debrief/tree/3875_improve_reset_time_format

Please, confirm if you can reproduce what you mention in your review.
Thanks.
Saul

**Comment by helenayele** [comment]
Verified
