### ISSUE TITLE
Inactive selected tracks in Select Tracks Combo of XY Graph

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4080]
I still see false selected tracks (they are selected but also inactive) in select combo , see this video:

[![Image from Gyazo](https://i.gyazo.com/4d71933e7791c8fbb14c5e84c43e5ec7.gif)](https://gyazo.com/4d71933e7791c8fbb14c5e84c43e5ec7)

### Steps to reproduce:
1. Load sample.dpf
2. Select Rel Brg graph
3. In the select tracks combo -  select Nelson in display and CollingWood in relation to
4. Then unselect Nelson - See that CollingWood is inactive and selected.
But the graph is empty that means no track is selected - (But we are showing CollingWood is selected even if it is inactive)

**Comment by saulhidalgoaular** [comment]
Hi @helenayele 
I have implemented this behavior intentionally. It doesn't mean It is inactive when the checkbox is disabled. It means that the user would be unable to remove a track that has been selected as primary. If it is primary, we are sure we want that in the selected track list. I also think It was what the designer had in mind, according to the mockups created.

Graph is empty, because that operation is relative, which means It needs at least 2 tracks. Invalid selections will imply empty graphs.

**Comment by helenayele** [comment]
Okay clear - thanks
