### ISSUE TITLE
Change default Property window width

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4147]
The default property window size is not enough to show all the available actions. 
For example when I open the property of a position from Nelson_A:0500 layer, it looks like this :
[![Image from Gyazo](https://i.gyazo.com/3497bbc61251086c20f4857777aae4ba.png)](https://gyazo.com/3497bbc61251086c20f4857777aae4ba)

And when I increase the width , I can see one more hidden action 'Export Shape' . So the user will not have an idea about this action, and he/she can miss it.

[![Image from Gyazo](https://i.gyazo.com/9d5afabb7a369d9da0db5cb7bca42113.gif)](https://gyazo.com/9d5afabb7a369d9da0db5cb7bca42113)

**Comment by IanMayo** [comment]
## Note:
an alternate strategy to making the dialog wider, is to fix the layout issue.  I _think_ the 4th button disappears because it has been wrapped to a second line. But, the header area can't/won't grow taller to show the second row.

So, I think the layout should make the button area grow taller if they don't all fit on one line.

**Comment by ayeshare** [comment]
@saulhidalgoaular @IanMayo, Since this pr was not assigned, I created a branch and increased the window width. I see there are other fixes, please feel free to ignore my fix

**Comment by IanMayo** [comment]
@ayeshare - sure.

**Comment by helenayele** [comment]
Verified
