### ISSUE TITLE
Show Symbol property of xy graph is not working for Rep files

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4168]
Show symbol property is not working for rep files both in Full debrief and D-Lite.
[![Image from Gyazo](https://i.gyazo.com/261a63f23e775179c698eb3870442de1.gif)](https://gyazo.com/261a63f23e775179c698eb3870442de1)

### Steps to reproduce:
1. Launch D-Lite
2. Open boat1.rep
3. Select Speed graph type and select the track
4. when the graph is seen, select Show Symbol button on the toolbar to show the symbols.

**Comment by saulhidalgoaular** [comment]
Good morning @IanMayo 

Short question: Would you prefer me to at add a new variable in the FixWrapper to indicate that we want to show the symbol in XY Plot, or I show the symbols in the XY Plots and regular plot for all reps?

Documentation of the question:

I have finished analyzing this issue, because I had it almost done.
Origin of this behavior is that we are showing the ticks (symbols) in the XY plots only when: show symbol of the specific FixWrapper is activated, or Show Arrow is activated.
However, for .reps with only trackdata, none of them are activated.

I have analyzed this situation for a similar case, and I see that for planning legs you have rechecked and manually enabled the show symbol to each FixWrapper, generating a plot like this:

![image](https://user-images.githubusercontent.com/11049943/62582119-99c12080-b8ab-11e9-9c04-0c50660a20c7.png)

Do you want this behavior for .rep with only TrackData or Do you prefer a special variable to specify whether the symbol is drawn?

**Comment by saulhidalgoaular** [comment]
Key lines of code to re-check/resume:
ShowTimeVariablePlot3.java@425
ColouredDataItem.java@108

**Comment by IanMayo** [comment]
Ok, now we understand the cause.  We're only showing a marker if there is a symbol/arrow visible at that data point.

In that case, I don't think there's an issue - since we're seeing the intended behaviour.

**Comment by helenayele** [comment]
So this means it is expected that show symbol property doesn't work for Rep files , right? if so can we remove this 'Show symbols' property both from graph toolbar and from graph property window?
[![Image from Gyazo](https://i.gyazo.com/d75bb8031e0de6b1c4175109a231ba38.gif)](https://gyazo.com/d75bb8031e0de6b1c4175109a231ba38)

**Comment by IanMayo** [comment]
No, we don't need to remove them. If we show a symbol every 15 minutes for the rep track, we can then switch symbol on in the graph.  But, since rep files (by default) don't have any symbols set to visible on load, they don't Surat in the graph either

**Comment by helenayele** [comment]
I just set label frequency for both tracks of about 15 minutes, and try to use show symbol property on the graph , but symbols are not shown on the graph

[![Image from Gyazo](https://i.gyazo.com/81221b0dca7dac33ae5df0b33eac05b3.gif)](https://gyazo.com/81221b0dca7dac33ae5df0b33eac05b3)

**Comment by helenayele** [comment]
Verified - The show symbol property now works for rep files if tracks arrow frequency or symbol frequency is set.
