### ISSUE TITLE
Expand shapes by default during insertion

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4230]
When user adds shape using insert menu, the shapes are not fully shown unless user expands them using Fit to window action. It will be very handy for the user if the shapes gets expanded as soon as user inserts them.

Video:
[![Image from Gyazo](https://i.gyazo.com/8d00ff4a9d1340f92f959d32b242afcb.gif)](https://gyazo.com/8d00ff4a9d1340f92f959d32b242afcb)

**Comment by helenayele** [comment]
Verified

**Comment by IanMayo** [comment]
I think the implementation may have been mistaken on this one.  This is the desired behaviour:
* if this is the first data loaded, then resize, to "zoom in" on that shape
* if data has already been loaded, then don't resize - since we're already covering the area of the new shape

We can tell if data has already been loaded, by checking if the visible displayed area matches that originally set when the application started.

**Comment by helenayele** [comment]
Working fine - Verified.
