### ISSUE TITLE
Debrief-Lite projection/coordinate troubles

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4294]
In the new Debrief-Lite application `DebriefLiteApp.java`, we're introducing support for GeoTiff images in the `4280_handle_import_tif` branch.

![image](https://user-images.githubusercontent.com/1108513/60023164-2a8dc500-968d-11e9-92d5-79a6f91a3490.png)

While we're using JMapPane as the mapping component, we're doing some "wrapping" of it, since most of our data management/rendering is done within a mature library of non GeoTools code.

The developer has supported drag/drop of the GeoTiff into the application, but the image doesn't  appear.

I've traced the logic, and have found out that we had two separate MapContent objects.

I've refactored the code, so that our content is all put into the same MapContent instance.

We can load the Image, but we're now working with two units systems.  I _think_ when we load GeoTools data it's using metres of lat/long. But, when we load/display Debrief data, it's using degrees of lat/long - so the data is all visible, but in two different projections at the same time.

Here is the display of units:
![image](https://user-images.githubusercontent.com/1108513/60023186-32e60000-968d-11e9-9d24-cd7e5e008d5e.png)

A zip containing a sample track file is attached, which can be drag/dropped into the application.
[UK_Track.zip](https://github.com/debrief/debrief/files/3321084/UK_Track.zip)

I can provide a sample GeoTiff image, for use in Debugging.

**Comment by ianturton** [comment]
It does look as if the GeoTiff is in EPSG:27700 and it has changed the projection of the map to match it rather than the other way around. If you can let me have a copy of the tiff I'll take a look.

**Comment by IanMayo** [comment]
Image sent via email at 14:49.

**Comment by ianturton** [comment]
If I drag and drop the image into the current build - I get a different view than you.

![Screenshot from 2019-06-27 18-26-43](https://user-images.githubusercontent.com/122529/60287182-28d03580-9909-11e9-931d-d002f6b313d4.png)

So it looks like the map stays in degrees and there is no problem with the coordinate read out. However, if I try to use the menu to import the tiff then I get a reprojection exception probably because the map is in degrees but the incoming tiff isn't. 

Am I right in thinking the map should change projection when a new file is added? if so can you point me to where that should happen?

**Comment by IanMayo** [comment]
That's great progress.  Phew.

The drag vs import is a surprise, I'd assume they used the same code.  Let me/us investigate.

I _think_ the issue is when we drag in a track file (there's on the zip file at the start of this thread).  I think that sends the coordinates screwy.

I've attached an image of where the track should be.
![Track in UK waters](https://user-images.githubusercontent.com/1108513/60287761-9b8de080-990a-11e9-98c7-451167393e00.png)

**Comment by IanMayo** [comment]
Issue sorted, thanks to @ianturton
