### ISSUE TITLE
DLite Testing - test strategy

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4417]
I'd like Helen to have a look through the GeoTools Robot-based testing. 

The tests are all under this folder:
https://github.com/geotools/geotools/tree/master/modules/unsupported/swing/src/test/java/org/geotools/swing

It will be useful to learn what types of things can be tested with this technique.

Once we know what can be listed, Helen can produce a _shopping list_ of UI tests for Debrief-Lite, for another team member to work on.

**Comment by helenayele** [comment]
Hey @IanMayo , hope everything goes well. I try to see the tests under the above url - they are junit tests. And I try to read about Robot Framework. And it is a bit different testing framework - It is keyword based testing framework a bit easy for end user to write the tests. 
So I want to be clear with your requirement, I think you need me to first see the tests under this url and based on this you want me to write appropriate tests for D-Lite in Robot Framework?

**Comment by ayeshare** [comment]
@IanMayo after talking to @helenayele, Robot framework seems it is meant for testers to write automation test cases.  It uses Jython.  It is pretty straightforward.  Since we are using Ribbon it seems we wont be able to use that framework.  I wrote a test case that we can test buttons in the outline view.  These automation test cases can only supplement unit test cases.  It is keyword driven and we have keywords for basic swing components like tree,table, button, dropdown box, list box, etc

**Comment by IanMayo** [comment]
@ayeshare - we discussed this in Slack.

I believe Robot isn't suited to us, but we'll do plain Junit testing of the UI elements, similar to how it's performed in GeoTools.

**Comment by IanMayo** [comment]
Done.
