### ISSUE TITLE
[8] Display using symbols and show track names are kinda hidden

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4544]
User comment
`Display using symbols and show track names are kinda hidden`

_Ian's comment "Hmm, I can’t tell if it’s related to normal/snail trail highlighting, or to showing symbols on a track.  Maybe it’s because the highlighters are hidden down in the Time Properties editor.
I think there’s probably a justification to also be able to edit them from new icons/controls/buttons on the Time ribbon bar."_

Show track names is found in the Time properties window but Display symbols types is applied in Snail mode and found in the main track property window. This I think confuses user

**Comment by IanMayo** [comment]
@helenayele - I now understand this issue.  Switching on the `Display track name` in snail mode isn't directly accessible . The analyst has to click on `Time Properties`, then `Edit display mode`. We could just have a `Config` button next to the `Normal`/`Snail` toggle buttons, that opens the dialog for the current display mode.

The other issue relates to switching between the `Symbol Highlighter` and `Default Highlighter` modes, with their separate configs.  I believe this should be another pair of toggle buttons in the Time Ribbon, with their own config button (which opens `Edit Highlighter`).

**Comment by IanMayo** [comment]
Here's a reminder for @Celine on the current workflow. The Time Bar has a `Properties` button:
![image](https://user-images.githubusercontent.com/1108513/65781210-20bfa600-e143-11e9-9a84-bc27bb34af77.png)

(the button is the one on the left. The one on the right is a format button, to choose the date format in use)

That opens this dialog:
![image](https://user-images.githubusercontent.com/1108513/65781233-2ae1a480-e143-11e9-9c82-5c3a3c333ce7.png)

On this dialog are two drop-downs. The first is for the `Display` mode, which allows the user to toggle between `Normal` and `Snail` mode:
![image](https://user-images.githubusercontent.com/1108513/65781338-5e243380-e143-11e9-8420-eecfd0ed3a60.png)

The second toggles between showing the rectangular highlight for `current time` the other for showing a symbol that relates to that vessel:
![image](https://user-images.githubusercontent.com/1108513/65781406-7d22c580-e143-11e9-8ac6-cb581fd93b81.png)

Clicking on `Edit highlighter` or `Edit display mode` opens a dialog that contains properties relevant to the current highlighter/display-mode.

We already have the toggle buttons for Normal/Snail display mode:
![image](https://user-images.githubusercontent.com/1108513/65782105-dfc89100-e144-11e9-954e-355c9dcfaa53.png)

My idea is to add a properties button to that panel, that will open the property dialog for that mode.

We would also add another "region" on the ribbon, for "Highlighter" that would include two toggles and a properties button.

**Comment by clenoble** [comment]
@IanMayo 
I agree it's best if the snail mode properties can be edited directly next to the snail mode button. 
The Normal mode properties are not editable, right?

The choice of highlighter and its properties don't seem at their place in the Time panel. They seem to be a property of objects on the map, rather than time sequence. When double-clicking on Track to open the track properties, you already have properties such as Snail symbol size, Snail symbol type. I think the highlighter should be located there. 
This way, the user could choose one highlighter for the primary track, and another one for the secondary track.

As a general comment, the property panels are quite complex. For Debrief lite, it might be worth it to have smaller panel with only the most used properties and an advanced button to go to the properties that are rarely changed. (That's something I thought of when reviewing Full Debrief too. This is also where stats on usage are useful to know which property to hide).

**Comment by IanMayo** [comment]
Oooh, that's clever @clenoble 

But, it's unclear whether users would rather have the customisability of being able to change the highlighter per-track, or the quick performance of being able to switch all the highlighters at once.

I'll send out a straw poll.

Simple vs Advanced properties.  Yes, I'll add that.

**Comment by IanMayo** [comment]
@clenoble - was adding task to identify simple properties, and found this:
https://github.com/debrief/debrief/issues/3915

I can have a look, but I didn't have much success back in March.

**Comment by IanMayo** [comment]
@clenoble - yes, Normal Mode doesn't have any properties.

Would you mind giving us an updated UX design for the Time Controller that includes the Display Mode properties?   Actually, since Normal Mode doesn't have properties, I guess we just need a "Snail Properties" button.

Still nothing back from users regarding whether highlight mode should be a per-track property.  If we don't hear back from them saying "per-track highlighting, please" then my preference would be to continue with the current strategy.  That's partially because we'll probably have to change the Full Debrief behaviour to match it, and some of my Full Debrief users fear change :-(

_If_ we end up keeping it at the whole-application level, then it does feel logical to have the properties in a "Task Group" next to the display modes. The feature that we're customising is how the platform position is displayed at the specified time, and this panel is where time is controlled. (IMHO...)

**Comment by clenoble** [comment]
![Snail-mode-properties](https://user-images.githubusercontent.com/22282418/66196234-77c00080-e698-11e9-9c7b-b6486e4b21cb.png)

Here is how I would imagine snail mode properties to work. the large button is to enable / disable snail point. The small triangle in the bottom left corner opens the property panel.

**Comment by clenoble** [comment]
Highlight is in fact always on, the question is more whether to use a simple square (default), or a symbol. 
If the user wants to edit the default highlighter, they have to do it in Time panel, if they want to edit the symbol size and type, they need to do it in the Outline panel, and it's per track. 

This is a rather complex process. I would simplify it by not giving so many options to the user. The default option would not be customizable and always on, unless a user goes into Outline and specify a symbol, size, color. Then, if and when a symbol is specified, it is automatically and always displayed for this track. If the user wants to go back to default, they have to remove the symbol for this track. 

This way, there can be a combination of symbols and squares, if the user wants to highlight a specific track compared to the others.

**Comment by IanMayo** [comment]
Ok. Nothing back from users.  I fear that putting the snail properties down per-track in the Outline would hide this capability.

I'd like us to do this:
* new section on Time Ribbon, titled `Highlighter`.  This is to go to the right of `Display Mode`.  This new ribbon will contain two Radio buttons: `Square` and `Symbol`. 
* the `Display Mode` and `Highlighter` panels should gain a `Properties` button.  This will open the respective properties panel (normal, snail, default-highlighter, symbol-highlighter).

**Comment by helenayele** [comment]
Now it looks like this :
[![Image from Gyazo](https://i.gyazo.com/7925b86e48117bc6a23d6d85e7128112.png)](https://gyazo.com/7925b86e48117bc6a23d6d85e7128112)

And a user can easily change the highlighter as well as some properties of a track in a snail mode.
Verified.
