### ISSUE TITLE
Display mode and highlighter buttons are not disabled on empty plot 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4644]
All the new Display mode buttons and highlighter buttons are kept enabled even if there is no any plot opened in the map panel.
[![Image from Gyazo](https://i.gyazo.com/6245cb31adae6bb48aae146456933bd5.gif)](https://gyazo.com/6245cb31adae6bb48aae146456933bd5)
 
But when I try to change some values in the property window doesn't throw Null pointer exception.

**Comment by IanMayo** [comment]
Helen, we don't have the concept of "no plot open".  In D-Lite, we always have a plot open. 

But, since we don't have time enabled (since no time-related data is loaded), it would make more sense for the display/highlight mode buttons (and their properties) to be disabled until time-related data is loaded.

**Comment by helenayele** [comment]
> Helen, we don't have the concept of "no plot open". In D-Lite, we always have a plot open.
Right, should say "No time related data is loaded" sorry for my wrong explanation here.

**Comment by helenayele** [comment]
Verified - Now they are disabled unless time related data is loaded on the plot.

**Comment by helenayele** [comment]
Verified in 4562_upgrade_flamingo branch as well
