### ISSUE TITLE
Plot doesn't take into account the previous end time set from Filter to Time control

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4799]
After I load the narrative.rep file and set filter to time to some value, I tried to load boat1.rep file. When I play the track, the track doesn't stop playing on configured end time on filter to time value. it just stops playing on the tracks end time rather than the configured end time on filter to time control.

[![Image from Gyazo](https://i.gyazo.com/7f942aab7becd08b51b7cf5ff3b7bf74.png)](https://gyazo.com/7f942aab7becd08b51b7cf5ff3b7bf74)

### Steps:
1. Load narrative.rep and set end time in Filter-to-Time to  09:23:XX
2. Load boa1.rep
3. Play the track

**Comment by helenayele** [comment]
@IanMayo  and @ayeshare  I should keep this issue as open as narrative entries are not loaded on the Narrative panel
[![Image from Gyazo](https://i.gyazo.com/80187e992f46c538a4731abd66b116a2.png)](https://gyazo.com/80187e992f46c538a4731abd66b116a2)

**Comment by saulhidalgoaular** [comment]
Good morning @helenayele 
I have tried the steps, but I cannot reproduce it. When I drag the `boat1.rep` , the filters are resetted and the narratives are shown. This is what happens when I try the steps:

![GifMaker_20200725074407925](https://user-images.githubusercontent.com/11049943/88452030-26ba0c80-ce64-11ea-86a0-e39770bbeaa4.gif)

Narratives are shown as expected.

Do you know the steps to arrive to the screenshot you showed at https://github.com/debrief/debrief/issues/4799#issuecomment-663494313

**Comment by helenayele** [comment]
I tried also to load narrative files like narrative.rep , and it loads the narrative entries on narrative panel without any issues.
Hence closing this issue.
[![Image from Gyazo](https://i.gyazo.com/9d32d39bf9bdd8dbae8f784e1305d465.gif)](https://gyazo.com/9d32d39bf9bdd8dbae8f784e1305d465)
