### ISSUE TITLE
Database import - UX feedback

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4854]
@clenoble had a few suggestions on the design: 

1. The modal is quite small, and it might be difficult to find something once the list of items is very long with many levels all maximized. Ideally, when looking at any child, you should be able to see the top parent in the same screen (no scrolling)
2. The apply and import buttons on the other hand are quite big.
3. The modal title is too small: it should be bigger as it's the highest item in the information hierarchy. (edited) 
4. For the list, arrows replace the plus and minus signs I used in the wireframes. I find the arrows more confusing than plus and minus, especially at the lowest level when there is no children, do you still have an arrow but it's disabled? With a minus sign, you can be sure you have reached the bottom of the tree.

**Comment by helenayele** [comment]
Now 
1. the modal size is modified and holds all the imported dbs. 
2. The apply and import buttons size is modified so that they have medium size
3. The modal title becomes large.
4. We still have the arrows, and when it is not expanded at all we show a greater than sign (>) and when it gets expanded we show ^ sign, and when it reaches leaf of the root, we show nothing.
And finally it looks like 
[![Image from Gyazo](https://i.gyazo.com/62bb9c343ff605051352c68d344752e4.png)](https://gyazo.com/62bb9c343ff605051352c68d344752e4)
