### ISSUE TITLE
Path of GeoTiff in DPF files not portable

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4964]
We can include GeoTiff images in our plots - analysts use this a lot.

Debrief stores the absolute path to the image in the `layerPath` attribute.  This is ok for multiple users when the images comes from a shared network folder, since the path probably matches.  But, it fails if the dpf plus GeoTiff are zipped up and sent to someone else.  

Another example of this is for the `sample_data` that we distribute with Debrief.  A new user can load a `.dpf` file which includes a GeoTiff file in the current folder, but Debrief will fail to load it.

How do we handle this?  

1. When saving an `externalDataFile` object, see if it's in the same folder as the `.dpf` file.  If it is, just use a relative reference
2. When loading an `externalDataFile` object, if the file-load fails, have another go, using a relative path reference.
3. If the above fails, get the absolute reference to the `.dpf` file and see if the image file is present in the same directory.  If it is, load it.

Hmm, but the issue may be that we don't know the default folder location that Debrief is using as `home directory`.

We should investigate this further, to see what the options are.

**Note**: a recent PR introduces a GeoTiff image file, and a `.dpf` file that refers to it.  The `.dpf` needs to be manually _fixed_ to work on each new PC it's stored on, because of the above issue:
https://github.com/debrief/debrief/pull/4963

**Comment by ayeshare** [comment]
@IanMayo Do we have to read from the zip file ? or does the user unzip the file and read it?

**Comment by IanMayo** [comment]
@ayeshare  - no, we don't need to unpack zip files.  The analyst will unpack the zip file.  But, because the `.dpf` stores an absolute path on their original drive the absolute reference probably won't be valid on the recipient's PC.

**Comment by ayeshare** [comment]
@IanMayo is there an example dpf file which has a tif file in it?

**Comment by IanMayo** [comment]
@ayeshare - yes, see the note at the end of the issue

The PR has now been merged, so the file(s) should be present in `develop`.

**Comment by IanMayo** [comment]
Working plot:
![image](https://user-images.githubusercontent.com/1108513/93467637-d7cda800-f8e5-11ea-9f42-375267cbe872.png)

Note: if the background image isn't shown, then Debrief may have failed to read the path.

**Comment by helenayele** [comment]
Currently it shows the tiff file when it is given absolute path like this in windows OS:<externalDatafile DataType="GeoTiff" LayerName="SP27GTIF.tif" LayerPath="D:\\Debrief materials\\DebriefNG-Windows64Bit\\DebriefNG\\sample_data\\SP27GTIF.tif" Visible="true"/>
and it accepts as well relative paths like 
<externalDatafile DataType="GeoTiff" LayerName="SP27GTIF.tif" LayerPath=SP27GTIF.tif" Visible="true"/> when both files are found in the same folder.
But the problem I am seeing is (may be different issue), After following these steps the tiff file couldn't be loaded:
### Steps :
1. Open PlotWithGeoTiff.dpf file in text editor and set the layerPath nonexistent path
2. Open PlotWithGeoTiff.dpf  in Debrief plot editor , see that you get a dialog that states that it couldn't get the tiff file - okay
3. Close the dialog and try to drag the tiff file on the file
it looks like this in video:
[![Image from Gyazo](https://i.gyazo.com/2d7195c0e93c65898dde68783c764ab6.gif)](https://gyazo.com/2d7195c0e93c65898dde68783c764ab6)
as can be seen, it seems it loads the tiff file but finally the Tiff file is not loaded and when I open it after saving the dpf file, it didn't edit the layerPath part.
Due to this re-opening it .....
I expect after dragging the tiff file it should be loaded in the dpf file and shown without any issues and also layerPath should be modified with the new location.

**Comment by IanMayo** [comment]
@ayeshare  - I've just been working with a plot-file that isn't in a Debrief project, it's just in the file-system.  When I change the folder name the DPF fails to find the chart images.  I'll put the plot & TIFFs into Slack.

Steps to reproduce:
1. Unzip zip-file
2. Open DPF file. Observe that chart images aren't visible, and that log shows Debrief failed to find the TIFF

The issue can be _fixed_ by deleting the charts from Outline View, then dragging them back in.  But, the underlying problem needs to be fixed. i.e. When Debrief can't find a tiff, check for it in the plot-file's folder.

**Comment by helenayele** [comment]
The tiff files are loaded without any issues both from navigator in eclipse workspace and from file system from windows file browser.

Verified.
