### ISSUE TITLE
GeoPDF - Change structure of the Compose file

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4973]
Currently the compose file is created using Line, Labels, Markers and first point structure. I propose changing this structure to render FixWrappers independently. It will give the flexibility of changing the color/shape to each point individually, to represent a final result more similar to the original Debrief file.

**Comment by IanMayo** [comment]
The next stage of the GeoPDF is to do dynamic tracks - where the user can replay the track in Acrobat Reader.

For that step, the structure of the data will change - since all of the data in each time step has to be a "Layer" in the PDF document.

The new data structures are defined here:
https://docs.google.com/document/d/1Wcj75NjeSYcEW2jzf0s8L-3H2MEVC1zDlyDgjrOMxSc/edit#heading=h.t8e2ojxbh3se

So, it may be worth holding back on changing the structure until after that set of changes is implemented.
