### ISSUE TITLE
Make Metafile Canvas implement ExtendedCanvasType

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#538]
*[Migrated from Assembla ticket [540](https://www.assembla.com/spaces/Debrief/tickets/540) - reported by @IanMayo on 2013-12-06 16:09:50]*

Our SWT canvas implements ExtendedCanvasType, which indicates that it allows semi-transparent fills.

It would be great if MetafileCanvas also had implementations for those methods, so a copied plot looks like it does on the screen.

After a quick look, it appears that the implementation will actually be down in the WMF class.

But, "semi-transparent" fills may be practically impossible in WMF.  If it is, we won't do it.

**Comment by IanMayo** [comment]
@pecko  - could you investigate what is needed for us to plot our new "Sensor Coverage Arcs" to WMF?

I'm sure our fill(Shape) method call isn't in our WMF wrapper class - we could do with some options.

If eventually it's impossible to support Shape() plotting, then our Sensor Coverage class will have to produce a filled polygon instead of a Shape object.

**Comment by pecko** [comment]
I have added fill(Shape) to our WMF wrapper class.
The PR: https://github.com/debrief/debrief/pull/1228

The screenshot:

![image](https://cloud.githubusercontent.com/assets/534584/7546677/d5dfa72c-f5e0-11e4-8861-6a0cf2748bd3.png)

**Comment by IanMayo** [comment]
@Peco - great algorithm you have there to convert a Shape to a Polygon. Well done.

Grr, sorry - my description of the issue was too short.

If possible, I would like to support both semiFillShape and fillShape operations in WMF.

Actually, if it is possible to support semi-transparent in WMF we could let MetafileCanvas implement all of ExtendedCanvasType.

That would be great for WMF users.

Do you think this is possible?

**Comment by IanMayo** [comment]
@Peco - could you also double-check the export to WMF support under MS Windows. I get the sensor arcs exported to file when I do a MS Windows "screenshot" export (ctrl-C).  But, I don't get the arcs when I do "Export WMF to clipboard".

Here is the plot in Debrief:
![debriefscreenshot](https://cloud.githubusercontent.com/assets/1108513/7565966/1e35549c-f7ec-11e4-8b4d-11f9f406d65e.png)


And here is what got pasted from the clipboard:
![inwordpad](https://cloud.githubusercontent.com/assets/1108513/7565973/2cfeb220-f7ec-11e4-86da-ec4a72a7b1ac.png)

**Comment by pecko** [comment]
> @Peco - could you also double-check the export to WMF support under MS Windows. I get the sensor > arcs exported to file when I do a MS Windows "screenshot" export (ctrl-C). But, I don't get the arcs  when I do "Export WMF to clipboard".

Ctrl-C doesn't export plot as WMF. Is is bitmap for all platforms. 
The "Export WMF to clipboard" copies WMF to clipboard and there is only on Win 32-bit
See https://github.com/debrief/debrief/issues/1073

Will check on Win 32-bit shortly.

**Comment by pecko** [comment]
It works. You probably don't apply the PR: https://github.com/debrief/debrief/pull/1228

The screencast:

![image](https://cloud.githubusercontent.com/assets/534584/7578113/b5c8e51c-f850-11e4-8f8a-1308083bdcbe.png)

**Comment by IanMayo** [comment]
Yes - you're quite right - hadn't applied the correct PR. Sorry :-(

#1228 merged.

**Comment by IanMayo** [comment]
Great. Next step - can we have semi-transparent shaded areas?

**Comment by pecko** [comment]
> Great. Next step - can we have semi-transparent shaded areas?

I have explored that a long time ago without success. WMF certainly supports transparency (color has 4 dimensions r, g, b and alpha in specification), but I don't find how to implement. Will check again...

**Comment by IanMayo** [comment]
Aah yes, of course - I remember.
