### ISSUE TITLE
Localisation of date format in Maintain Contributions View

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#637]
In the Maintain Contributions view is a series of contributions. Most of these include start/end date-time.

The date widget is mistakenly showing the date as Month/Day/Year.  My user community expects the order to be in Day/Month/Year.

Here is an example:
![datetimewidgetformat](https://cloud.githubusercontent.com/assets/1108513/3241795/14014140-f142-11e3-940c-dec925ce94ab.png)

To reproduce the problem:
1. open Debrief then open the Sample Data/SATC/CompositeStraightTest.xml file.
1. Then open the **Maintain Contributions** view
1. Then select the **121213.14** solution in the layer manager.  
1. The **Maintain Contributions** view will open.  Open the second item: **Straight Leg Forecast - first leg COMPOSITE**

The two dates in the **Dates** line should be in the form day/month/year, not month/day/year.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1092

I have added required nebula plugins (o.e.nebula.cwt, o.e.nebula.jface.cdatetime and o.e.nebula.widget.cdatetime) to o.m.cmap.combined.feature because, IMO, the nebula cdatetime update site isn't enough stable.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/534584/6098195/ceb027b4-afd7-11e4-8ee9-e3df326babc3.png)
